name: Deploy to VPS without Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/deploy/app/app-graphql"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
          
            cd /home/deploy/app/app-graphql
            docker stop myapp || true
            docker rm myapp || true
            # Construir la nueva imagen
            docker build -t myapp:latest .
            # Ejecutar el nuevo contenedor
            docker run -d --name myapp -p 80:8080 myapp:latest
