name: Deploy to VPS without Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync files to VPS using rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: "-avz --delete --filter=': .rsync-filter'"
          path: ./
          remote_path: /home/deploy/app/app-graphql
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and deploy app on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/app/app-graphql
            npm install
            npm run build
            docker stop myapp || true
            docker rm myapp || true
            docker build -t myapp:latest .
            docker run -d --restart always --name myapp -p 3000:3000 myapp:latest


